version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres

    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: my_todo_database_user
      POSTGRES_USER: dAddn2AXFFxnaSjtwiOBj4G43MHuZMeQ
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres
    restart: always

  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '8001:8001'
    command: sh -c "npm run db:migrate && npm run db:push && npm run seed && npm run dev"
    depends_on:
      - postgres
    restart: always

volumes:
  pgdata: