export enum TodoStatusCodes {
  TODO_CREATED_SUCCESSFULLY = 201,
  TODO_UPDATED_SUCCESSFULLY = 200,
  TODO_DELETED_SUCCESSFULLY = 200,
  TODO_GOT_SUCCESSFULLY = 200,
  TODO_GOT_LIST_SUCCESSFULLY = 200,
  TODO_BAD_REQUEST = 400,
}
